-- Jeu de donnees initial des quiz : recupere dans assets/js/quiz.js (test de
-- niveau) et dans l'ancien ui/pages/quiz/quiz.html (grammaire, vocabulaire,
-- comprehension). A appliquer APRES migrations/2026_09_29_add_quiz_tables.sql.
-- Sans ces questions, le menu des quiz n'affiche rien et le test de niveau est vide.

INSERT INTO `quiz_questions` (`categorie`, `libelle_categorie`, `niveau`, `difficulte`, `question`, `explication`, `date_creation`) VALUES
  ('niveau', 'Test de niveau', 'tous', 'a1', 'Comment dit-on \'Hello\' en français ?', NULL, '2026-09-29 13:00:00'),
  ('niveau', 'Test de niveau', 'tous', 'a1', 'Complètez : \'Je ___ français.\'', NULL, '2026-09-29 13:00:00'),
  ('niveau', 'Test de niveau', 'tous', 'a2', 'Quel temps fait-il ? \'Il ___ beaucoup.\'', NULL, '2026-09-29 13:00:00'),
  ('niveau', 'Test de niveau', 'tous', 'a2', 'Complétez : \'Nous ___ aller au cinéma ce soir.\'', NULL, '2026-09-29 13:00:00'),
  ('niveau', 'Test de niveau', 'tous', 'b1', 'Complétez : \'Si tu ___ riche, tu voyagerais.\'', NULL, '2026-09-29 13:00:00'),
  ('niveau', 'Test de niveau', 'tous', 'b1', 'Quel est le participe passé de \'finir\' ?', NULL, '2026-09-29 13:00:00'),
  ('niveau', 'Test de niveau', 'tous', 'b2', 'Choisissez le subjonctif : \'Il faut que tu ___ ton travail.\'', NULL, '2026-09-29 13:00:00'),
  ('niveau', 'Test de niveau', 'tous', 'b2', 'Identifiez le mode verbal : \'Pourvu qu\'il vienne!\'', NULL, '2026-09-29 13:00:00'),
  ('niveau', 'Test de niveau', 'tous', 'c1', 'Identifiez la figure de style : \'La nuit, les chats sont gris.\'', NULL, '2026-09-29 13:00:00'),
  ('niveau', 'Test de niveau', 'tous', 'c1', 'Choisissez le bon registre : \'Je t\'aime\' (registre littéraire)', NULL, '2026-09-29 13:00:00'),
  ('grammaire', 'Grammaire', 'a1', 'a1', 'Quel est le féminin de \'grand\' ?', NULL, '2026-09-29 13:00:00'),
  ('grammaire', 'Grammaire', 'a2', 'a2', 'Le passé composé de \'aller\' est :', NULL, '2026-09-29 13:00:00'),
  ('grammaire', 'Grammaire', 'b1', 'b1', 'Le plus-que-parfait de \'finir\' :', NULL, '2026-09-29 13:00:00'),
  ('grammaire', 'Grammaire', 'b2', 'b2', 'Le subjonctif après \'il faut que\' :', NULL, '2026-09-29 13:00:00'),
  ('vocabulaire', 'Vocabulaire', 'a1', 'a1', '\'La maison\' en anglais :', NULL, '2026-09-29 13:00:00'),
  ('vocabulaire', 'Vocabulaire', 'a2', 'a2', '\'Faire les courses\' signifie :', NULL, '2026-09-29 13:00:00'),
  ('vocabulaire', 'Vocabulaire', 'b1', 'b1', '\'Par ailleurs\' est un connecteur de :', NULL, '2026-09-29 13:00:00'),
  ('comprehension', 'Compréhension', 'a1', 'a1', 'Texte : \'Je m\'appelle Marie. J\'ai 20 ans.\' Quel âge a Marie ?', NULL, '2026-09-29 13:00:00'),
  ('comprehension', 'Compréhension', 'a2', 'a2', 'Dialogue : \'Où est la gare ? - C\'est à droite.\' La gare est :', NULL, '2026-09-29 13:00:00'),
  ('comprehension', 'Compréhension', 'b1', 'b1', 'Article : \'Malgré la crise, l\'économie croît.\' Le contexte est :', NULL, '2026-09-29 13:00:00');

-- Propositions : une ligne par proposition, est_correcte = 1 pour la bonne reponse.
INSERT INTO `quiz_propositions` (`question_id`, `libelle`, `est_correcte`, `ordre`) VALUES
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Comment dit-on \'Hello\' en français ?'), 'Bonjour', 1, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Comment dit-on \'Hello\' en français ?'), 'Au revoir', 0, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Comment dit-on \'Hello\' en français ?'), 'Merci', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Comment dit-on \'Hello\' en français ?'), 'Bonsoir', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Complètez : \'Je ___ français.\''), 'suis', 1, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Complètez : \'Je ___ français.\''), 'es', 0, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Complètez : \'Je ___ français.\''), 'sommes', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Complètez : \'Je ___ français.\''), 'êtes', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Quel temps fait-il ? \'Il ___ beaucoup.\''), 'fait', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Quel temps fait-il ? \'Il ___ beaucoup.\''), 'fait beau', 0, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Quel temps fait-il ? \'Il ___ beaucoup.\''), 'pleut', 1, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Quel temps fait-il ? \'Il ___ beaucoup.\''), 'y a', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Complétez : \'Nous ___ aller au cinéma ce soir.\''), 'allons', 1, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Complétez : \'Nous ___ aller au cinéma ce soir.\''), 'aller', 0, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Complétez : \'Nous ___ aller au cinéma ce soir.\''), 'allez', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Complétez : \'Nous ___ aller au cinéma ce soir.\''), 'va', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Complétez : \'Si tu ___ riche, tu voyagerais.\''), 'es', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Complétez : \'Si tu ___ riche, tu voyagerais.\''), 'serais', 0, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Complétez : \'Si tu ___ riche, tu voyagerais.\''), 'étais', 1, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Complétez : \'Si tu ___ riche, tu voyagerais.\''), 'seras', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Quel est le participe passé de \'finir\' ?'), 'finissant', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Quel est le participe passé de \'finir\' ?'), 'fini', 1, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Quel est le participe passé de \'finir\' ?'), 'finie', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Quel est le participe passé de \'finir\' ?'), 'finirez', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Choisissez le subjonctif : \'Il faut que tu ___ ton travail.\''), 'fais', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Choisissez le subjonctif : \'Il faut que tu ___ ton travail.\''), 'fasses', 1, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Choisissez le subjonctif : \'Il faut que tu ___ ton travail.\''), 'fait', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Choisissez le subjonctif : \'Il faut que tu ___ ton travail.\''), 'faire', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Identifiez le mode verbal : \'Pourvu qu\'il vienne!\''), 'Indicatif', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Identifiez le mode verbal : \'Pourvu qu\'il vienne!\''), 'Subjonctif', 1, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Identifiez le mode verbal : \'Pourvu qu\'il vienne!\''), 'Conditionnel', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Identifiez le mode verbal : \'Pourvu qu\'il vienne!\''), 'Impératif', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Identifiez la figure de style : \'La nuit, les chats sont gris.\''), 'Métaphore', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Identifiez la figure de style : \'La nuit, les chats sont gris.\''), 'Personnification', 0, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Identifiez la figure de style : \'La nuit, les chats sont gris.\''), 'Oxymore', 1, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Identifiez la figure de style : \'La nuit, les chats sont gris.\''), 'Euphémisme', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Choisissez le bon registre : \'Je t\'aime\' (registre littéraire)'), 'Je t\'affectionne', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Choisissez le bon registre : \'Je t\'aime\' (registre littéraire)'), 'Je t\'adore', 0, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Choisissez le bon registre : \'Je t\'aime\' (registre littéraire)'), 'Mon cœur palpite pour toi', 1, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'niveau' AND niveau = 'tous' AND question = 'Choisissez le bon registre : \'Je t\'aime\' (registre littéraire)'), 'Je te suis attaché', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'a1' AND question = 'Quel est le féminin de \'grand\' ?'), 'grande', 1, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'a1' AND question = 'Quel est le féminin de \'grand\' ?'), 'grands', 0, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'a1' AND question = 'Quel est le féminin de \'grand\' ?'), 'grand', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'a1' AND question = 'Quel est le féminin de \'grand\' ?'), 'grandir', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'a2' AND question = 'Le passé composé de \'aller\' est :'), 'allé', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'a2' AND question = 'Le passé composé de \'aller\' est :'), 'suis allé', 1, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'a2' AND question = 'Le passé composé de \'aller\' est :'), 'étais allé', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'a2' AND question = 'Le passé composé de \'aller\' est :'), 'ai alllé', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'b1' AND question = 'Le plus-que-parfait de \'finir\' :'), 'avait fini', 1, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'b1' AND question = 'Le plus-que-parfait de \'finir\' :'), 'eut fini', 0, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'b1' AND question = 'Le plus-que-parfait de \'finir\' :'), 'aurait fini', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'b1' AND question = 'Le plus-que-parfait de \'finir\' :'), 'finissait', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'b2' AND question = 'Le subjonctif après \'il faut que\' :'), 'infinitif', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'b2' AND question = 'Le subjonctif après \'il faut que\' :'), 'conditionnel', 0, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'b2' AND question = 'Le subjonctif après \'il faut que\' :'), 'subjonctif', 1, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'grammaire' AND niveau = 'b2' AND question = 'Le subjonctif après \'il faut que\' :'), 'indicatif', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'vocabulaire' AND niveau = 'a1' AND question = '\'La maison\' en anglais :'), 'mouse', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'vocabulaire' AND niveau = 'a1' AND question = '\'La maison\' en anglais :'), 'house', 1, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'vocabulaire' AND niveau = 'a1' AND question = '\'La maison\' en anglais :'), 'home', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'vocabulaire' AND niveau = 'a1' AND question = '\'La maison\' en anglais :'), 'spouse', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'vocabulaire' AND niveau = 'a2' AND question = '\'Faire les courses\' signifie :'), 'faire du sport', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'vocabulaire' AND niveau = 'a2' AND question = '\'Faire les courses\' signifie :'), 'acheter des provisions', 1, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'vocabulaire' AND niveau = 'a2' AND question = '\'Faire les courses\' signifie :'), 'courir', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'vocabulaire' AND niveau = 'a2' AND question = '\'Faire les courses\' signifie :'), 'faire la cuisine', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'vocabulaire' AND niveau = 'b1' AND question = '\'Par ailleurs\' est un connecteur de :'), 'temps', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'vocabulaire' AND niveau = 'b1' AND question = '\'Par ailleurs\' est un connecteur de :'), 'addition', 1, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'vocabulaire' AND niveau = 'b1' AND question = '\'Par ailleurs\' est un connecteur de :'), 'opposition', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'vocabulaire' AND niveau = 'b1' AND question = '\'Par ailleurs\' est un connecteur de :'), 'cause', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'comprehension' AND niveau = 'a1' AND question = 'Texte : \'Je m\'appelle Marie. J\'ai 20 ans.\' Quel âge a Marie ?'), '10 ans', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'comprehension' AND niveau = 'a1' AND question = 'Texte : \'Je m\'appelle Marie. J\'ai 20 ans.\' Quel âge a Marie ?'), '20 ans', 1, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'comprehension' AND niveau = 'a1' AND question = 'Texte : \'Je m\'appelle Marie. J\'ai 20 ans.\' Quel âge a Marie ?'), '30 ans', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'comprehension' AND niveau = 'a1' AND question = 'Texte : \'Je m\'appelle Marie. J\'ai 20 ans.\' Quel âge a Marie ?'), '25 ans', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'comprehension' AND niveau = 'a2' AND question = 'Dialogue : \'Où est la gare ? - C\'est à droite.\' La gare est :'), 'à gauche', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'comprehension' AND niveau = 'a2' AND question = 'Dialogue : \'Où est la gare ? - C\'est à droite.\' La gare est :'), 'à droite', 1, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'comprehension' AND niveau = 'a2' AND question = 'Dialogue : \'Où est la gare ? - C\'est à droite.\' La gare est :'), 'devant', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'comprehension' AND niveau = 'a2' AND question = 'Dialogue : \'Où est la gare ? - C\'est à droite.\' La gare est :'), 'derrière', 0, 4),
  ((SELECT id FROM quiz_questions WHERE categorie = 'comprehension' AND niveau = 'b1' AND question = 'Article : \'Malgré la crise, l\'économie croît.\' Le contexte est :'), 'négatif', 0, 1),
  ((SELECT id FROM quiz_questions WHERE categorie = 'comprehension' AND niveau = 'b1' AND question = 'Article : \'Malgré la crise, l\'économie croît.\' Le contexte est :'), 'positif', 1, 2),
  ((SELECT id FROM quiz_questions WHERE categorie = 'comprehension' AND niveau = 'b1' AND question = 'Article : \'Malgré la crise, l\'économie croît.\' Le contexte est :'), 'neutre', 0, 3),
  ((SELECT id FROM quiz_questions WHERE categorie = 'comprehension' AND niveau = 'b1' AND question = 'Article : \'Malgré la crise, l\'économie croît.\' Le contexte est :'), 'inconnu', 0, 4);
