<?php
namespace App\Controllers;
use App\Models\User; use App\Models\Favori; use App\Models\Progression; use App\Models\ConsecutiveDays;
class Auth extends BaseController {
 public function login(\Base $f3){$tpl=\Template::instance();$errors=[];if($f3->get('VERB')==='POST'){$r=(new User($f3->get('DB')))->login(trim($f3->get('POST.username')),$f3->get('POST.password'));if(is_array($r)){$f3->set('SESSION.user',$r['username']);$f3->set('SESSION.user_id',$r['id']);$f3->reroute('/profile');return;}$errors[]=$r;}$f3->set('errors',$errors);$f3->set('title','Connexion');$f3->set('content',$tpl->render('pages/auth/login.html'));echo $tpl->render('layout.html');}
 public function logout($f3){$f3->clear('SESSION');$f3->reroute('/');}
 public function register(\Base $f3){$tpl=\Template::instance();$errors=[];if($f3->get('VERB')==='POST'){$r=(new User($f3->get('DB')))->registerUser(['nom'=>trim($f3->get('POST.name')),'prenom'=>trim($f3->get('POST.name2')),'username'=>trim((string)$f3->get('POST.username')),'email'=>trim($f3->get('POST.email')),'password'=>trim((string)$f3->get('POST.password')),'confirm_password'=>trim((string)$f3->get('POST.confirm_password'))]);if(isset($r['user'])){$f3->set('SESSION.user',$r['user']['username']);$f3->set('SESSION.user_id',$r['user']['id']);$f3->reroute('/profile');return;}$errors=$r['errors'];}$f3->set('errors',$errors);$f3->set('title',"S'inscrire");$f3->set('content',$tpl->render('pages/auth/register.html'));echo $tpl->render('layout.html');}
 public function profil(\Base $f3){$tpl=\Template::instance();if(!$f3->exists('SESSION.user_id')){$f3->reroute('/login');return;}$id=(int)$f3->get('SESSION.user_id');$db=$f3->get('DB');$client=(new User($db))->getById($id);if(!$client){$f3->reroute('/logout');return;}try{$days=(new ConsecutiveDays($db))->recordActivity($id);}catch(\Throwable $e){$days=1;}$f3->set('SESSION.consecutive_days',$days);$p=(new Progression($db))->getByUser($id);$f3->mset(['user'=>$client['username'],'client'=>$client,'favorisCount'=>count((new Favori($db))->getFavorisByUser($id)),'niveau'=>$p?$p['niveau_global']:'Non évalué','score'=>$p?$p['score_test_initial'].'/10':'-','title'=>'Mon Profil']);$f3->set('content',$tpl->render('pages/auth/profile.html'));echo $tpl->render('layout.html');}
 public function editProfile(\Base $f3){$tpl=\Template::instance();if(!$f3->exists('SESSION.user_id')){$f3->reroute('/login');return;}$c=(new User($f3->get('DB')))->getById($f3->get('SESSION.user_id'));if(!$c){$f3->reroute('/logout');return;}$f3->set('client',$c);$f3->set('title','Modifier mon Profil');$f3->set('content',$tpl->render('pages/auth/profile_edit.html'));echo $tpl->render('layout.html');}
 public function updateProfile(\Base $f3){$tpl=\Template::instance();if(!$f3->exists('SESSION.user_id')){$f3->reroute('/login');return;}$id=$f3->get('SESSION.user_id');$m=new User($f3->get('DB'));$errors=[];if($f3->get('VERB')==='POST'){$r=$m->updateProfile($id,['nom'=>trim($f3->get('POST.nom')),'prenom'=>trim($f3->get('POST.prenom')),'username'=>trim($f3->get('POST.username')),'email'=>trim($f3->get('POST.email')),'password'=>$f3->get('POST.password'),'confirm_password'=>$f3->get('POST.confirm_password')]);if(isset($r['success'])){$f3->set('SESSION.user',$r['user']['username']);$f3->reroute('/profile');return;}$errors=$r['errors'];}$f3->set('client',$m->getById($id));$f3->set('errors',$errors);$f3->set('title','Modifier mon Profil');$f3->set('content',$tpl->render('pages/auth/profile_edit.html'));echo $tpl->render('layout.html');}
}
